<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitXMLReporter -->
<testsuite ignored="0" hostname="LAPTOP-47KEHV7J" failures="1" tests="5" name="TestRunner4" time="83.316" errors="0" timestamp="2023-04-14T23:16:55 IST">
  <testcase classname="Organization.CreateOrganizationTest" name="CreateOrganization" time="11.81">
    <skipped/>
  </testcase> <!-- CreateOrganization -->
  <testcase classname="Organization.CreateOrganizationTest" name="CreateOrganization" time="6.027">
    <skipped/>
  </testcase> <!-- CreateOrganization -->
  <testcase classname="Organization.CreateOrganizationTest" name="CreateOrganization" time="6.278">
    <skipped/>
  </testcase> <!-- CreateOrganization -->
  <testcase classname="Organization.CreateOrganizationTest" name="CreateOrganization" time="5.386">
    <skipped/>
  </testcase> <!-- CreateOrganization -->
  <testcase classname="Organization.CreateOrganizationTest" name="CreateOrganization" time="4.989">
    <failure type="java.lang.AssertionError" message="expected [true] but found [false]">
      <![CDATA[java.lang.AssertionError: expected [true] but found [false]
at Organization.CreateOrganizationTest.CreateOrganization(CreateOrganizationTest.java:41)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
at java.base/java.lang.Thread.run(Thread.java:833)
... Removed 24 stack frames]]>
    </failure>
  </testcase> <!-- CreateOrganization -->
</testsuite> <!-- TestRunner4 -->
